### ISSUE TITLE
Pin distance

### ISSUE THREAD

**Issue by Bergerie** [roman-minyaylov/nodemcu-v3-fritzing#1]
The distance between the two pin rows of my LoLin NodeMcu V3 measures around 27.6 mm. The library however uses a pin row distance of 22.7mm Could this be corrected.

**Comment by tonivss** [comment]
You are right. Furthermore the diameter of the pins are to small. When producing a PCB with this, the board won't fit.

**Comment by n1k0m0** [comment]
yes... just printed pcb with that and realized both issues above...

**Comment by roman-miniailov** [comment]
Problem resolved.
